CREATE OR REPLACE FUNCTION STRENKOWSKIP.COUNT_SEANCE_TICKETS(
	seance INTEGER
) RETURN NUMBER
IS
	tickets INTEGER;
BEGIN
	SELECT count(*) INTO tickets FROM BILET WHERE BILET.ID_SEANSU = seance;
	RETURN tickets;
END COUNT_SEANCE_TICKETS;
