CREATE OR REPLACE FUNCTION STRENKOWSKIP.SUMMARY(
	period VARCHAR2
) RETURN NUMBER
IS
	amount NUMBER;
	tmp_amount NUMBER;
BEGIN
	amount := 0;
	FOR movie IN (SELECT ID_FILMU, TYTUŁ FROM FILM) LOOP
		FOR seance IN (SELECT ID_SEANSU FROM SEANS WHERE SEANS.ID_FILMU = movie.ID_FILMU AND EXTRACT(MONTH FROM SEANS.POCZĄTEK) = EXTRACT(MONTH FROM SYSDATE) AND EXTRACT(YEAR FROM SEANS.POCZĄTEK) = EXTRACT(YEAR FROM SYSDATE)) LOOP
			SELECT COUNT(ID_BILETU) INTO TMP_AMOUNT FROM BILET WHERE ID_SEANSU = seance.ID_SEANSU;
			amount := amount + tmp_amount;
		END LOOP;
	END LOOP;

	RETURN amount;
END SUMMARY;