-- STRENKOWSKIP.UŻYTKOWNIK definition

CREATE TABLE "STRENKOWSKIP"."UŻYTKOWNIK" 
   (        "ID_UŻYTKOWNIKA" NUMBER(*,0) NOT NULL ENABLE, 
        "NAZWISKO" VARCHAR2(100), 
        "IMIĘ" VARCHAR2(100), 
        "LOGIN" VARCHAR2(100) NOT NULL ENABLE, 
        "ID_ROLI" NUMBER(*,0) NOT NULL ENABLE, 
        "ID_ULGI" NUMBER(*,0), 
        "ADRES_ZAMIESZKANIA" VARCHAR2(100), 
        "PREMIA" FLOAT(126) DEFAULT 0, 
        "HASŁO" VARCHAR2(100) NOT NULL ENABLE, 
        "ID_PLACÓWKI" NUMBER(*,0), 
         CONSTRAINT "UZYTKOWNIK_PK" PRIMARY KEY ("ID_UŻYTKOWNIKA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
         CONSTRAINT "UŻYTKOWNIK_ULGA_FK" FOREIGN KEY ("ID_ULGI")
          REFERENCES "STRENKOWSKIP"."ULGA" ("ID_ULGI") ENABLE, 
         CONSTRAINT "UŻYTKOWNIK_PLACÓWKA_FK" FOREIGN KEY ("ID_PLACÓWKI")
          REFERENCES "STRENKOWSKIP"."PLACÓWKA" ("ID_PLACÓWKI") ENABLE, 
         CONSTRAINT "UŻYTKOWNIK_ROLA_FK" FOREIGN KEY ("ID_ROLI")
          REFERENCES "STRENKOWSKIP"."ROLA" ("ID_ROLI") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "STRENKOWSKIP"."UZYTKOWNIK_PK" ON "STRENKOWSKIP"."UŻYTKOWNIK" ("ID_UŻYTKOWNIKA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;



-- STRENKOWSKIP.ULGA definition

CREATE TABLE "STRENKOWSKIP"."ULGA" 
   (        "ID_ULGI" NUMBER(*,0) NOT NULL ENABLE, 
        "NAZWA" VARCHAR2(100) NOT NULL ENABLE, 
        "ZNIŻKA" FLOAT(126) NOT NULL ENABLE, 
         CONSTRAINT "ULGA_PK" PRIMARY KEY ("ID_ULGI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "STRENKOWSKIP"."ULGA_PK" ON "STRENKOWSKIP"."ULGA" ("ID_ULGI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;



-- STRENKOWSKIP.ARCHIWUM definition

CREATE TABLE "STRENKOWSKIP"."ARCHIWUM" 
   (        "ID_WPISU" NUMBER(*,0) NOT NULL ENABLE, 
        "TABELA" VARCHAR2(30) NOT NULL ENABLE, 
        "OPERACJA" VARCHAR2(20) NOT NULL ENABLE, 
        "UZYTKOWNIK" VARCHAR2(100) NOT NULL ENABLE, 
        "BLAD" VARCHAR2(1000), 
        "DATA" DATE NOT NULL ENABLE, 
         CONSTRAINT "ARCHIVE_PK" PRIMARY KEY ("ID_WPISU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "STRENKOWSKIP"."ARCHIVE_PK" ON "STRENKOWSKIP"."ARCHIWUM" ("ID_WPISU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;




-- STRENKOWSKIP.PRODUKT definition

CREATE TABLE "STRENKOWSKIP"."PRODUKT" 
   (        "ID_PRODUKTU" NUMBER(*,0) NOT NULL ENABLE, 
        "NAZWA" VARCHAR2(100) NOT NULL ENABLE, 
        "CENA" FLOAT(126) NOT NULL ENABLE, 
         CONSTRAINT "PRODUKT_PK" PRIMARY KEY ("ID_PRODUKTU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "STRENKOWSKIP"."PRODUKT_PK" ON "STRENKOWSKIP"."PRODUKT" ("ID_PRODUKTU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;




-- STRENKOWSKIP.PRODUKT_TRANSAKCJA definition

CREATE TABLE "STRENKOWSKIP"."PRODUKT_TRANSAKCJA" 
   (        "ID_POWIĄZANIA" NUMBER(*,0) NOT NULL ENABLE, 
        "ID_PRODUKTU" NUMBER(*,0) NOT NULL ENABLE, 
        "ID_TRANSAKCJI" NUMBER(*,0) NOT NULL ENABLE, 
        "ILOSC_PRODUKTU" NUMBER(*,0) DEFAULT 1 NOT NULL ENABLE, 
         CONSTRAINT "PRODUKT_TRANSAKCJA_PK" PRIMARY KEY ("ID_POWIĄZANIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
         CONSTRAINT "PRODUKT_TRANSAKCJA_TRANSAKCJA_FK" FOREIGN KEY ("ID_TRANSAKCJI")
          REFERENCES "STRENKOWSKIP"."TRANSAKCJA" ("ID_TRANSAKCJI") ON DELETE CASCADE ENABLE, 
         CONSTRAINT "PRODUKT_TRANSAKCJA_PRODUKT_FK" FOREIGN KEY ("ID_PRODUKTU")
          REFERENCES "STRENKOWSKIP"."PRODUKT" ("ID_PRODUKTU") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE OR REPLACE EDITIONABLE TRIGGER "STRENKOWSKIP"."NEW_TRANSACTION_TRIGGER" 
        AFTER 
    INSERT 
    ON PRODUKT_TRANSAKCJA
    FOR EACH ROW 
DECLARE 
        qty NUMBER;
BEGIN
        SELECT ILOSC INTO qty FROM PRODUCTS WHERE PRODUCTS.PRODUCT_ID = :NEW.ID_PRODUKTU;
        IF :NEW.ILOSC_PRODUKTU <= qty THEN
                UPDATE PRODUCTS SET PRODUCTS.ILOSC = qty - :NEW.ILOSC_PRODUKTU WHERE PRODUCTS.PRODUCT_ID = :NEW.ID_PRODUKTU;
        END IF;
END; 




/-- STRENKOWSKIP.TRANSAKCJA definition

CREATE TABLE "STRENKOWSKIP"."TRANSAKCJA" 
   (        "ID_TRANSAKCJI" NUMBER(*,0) NOT NULL ENABLE, 
        "DATA" TIMESTAMP (6) NOT NULL ENABLE, 
        "ID_NABYWCY" NUMBER(38,0), 
        "ID_SPRZEDAWCY" NUMBER(*,0) NOT NULL ENABLE, 
        "BILANS" FLOAT(126) NOT NULL ENABLE, 
         CONSTRAINT "TRANSAKCJA_PK" PRIMARY KEY ("ID_TRANSAKCJI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
         CONSTRAINT "TRANSAKCJA_UŻYTKOWNIK_FK" FOREIGN KEY ("ID_NABYWCY")
          REFERENCES "STRENKOWSKIP"."UŻYTKOWNIK" ("ID_UŻYTKOWNIKA") ENABLE, 
         CONSTRAINT "TRANSAKCJA_UŻYTKOWNIK_FK_1" FOREIGN KEY ("ID_SPRZEDAWCY")
          REFERENCES "STRENKOWSKIP"."UŻYTKOWNIK" ("ID_UŻYTKOWNIKA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "STRENKOWSKIP"."TRANSAKCJA_PK" ON "STRENKOWSKIP"."TRANSAKCJA" ("ID_TRANSAKCJI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
ALTER TRIGGER "STRENKOWSKIP"."NEW_TRANSACTION_TRIGGER" ENABLE;

CREATE UNIQUE INDEX "STRENKOWSKIP"."PRODUKT_TRANSAKCJA_PK" ON "STRENKOWSKIP"."PRODUKT_TRANSAKCJA" ("ID_POWIĄZANIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


-- STRENKOWSKIP.BILET definition

CREATE TABLE "STRENKOWSKIP"."BILET" 
   (        "ID_BILETU" NUMBER(*,0) NOT NULL ENABLE, 
        "ID_SEANSU" NUMBER(*,0) NOT NULL ENABLE, 
         CONSTRAINT "BILET_PK" PRIMARY KEY ("ID_BILETU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
         CONSTRAINT "BILET_SEANS_FK" FOREIGN KEY ("ID_SEANSU")
          REFERENCES "STRENKOWSKIP"."SEANS" ("ID_SEANSU") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE OR REPLACE EDITIONABLE TRIGGER "STRENKOWSKIP"."ARCHIVE_TICKET" 
        BEFORE INSERT OR UPDATE OR DELETE ON BILET
        FOR EACH ROW
DECLARE
        method_name VARCHAR2(10);
BEGIN
        method_name := CASE
                WHEN INSERTING THEN 'INSERT'
                WHEN UPDATING THEN 'UPDATE'
                WHEN DELETING THEN 'DELETE'
        END;
        dbms_output.put_line(method_name);
        dbms_output.put_line(USER);
        CREATE_ARCHIVE_ENTRY(USER, method_name, '', 'BILET');
END;
/
ALTER TRIGGER "STRENKOWSKIP"."ARCHIVE_TICKET" ENABLE;

CREATE UNIQUE INDEX "STRENKOWSKIP"."BILET_PK" ON "STRENKOWSKIP"."BILET" ("ID_BILETU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;



-- STRENKOWSKIP.FILM definition

CREATE TABLE "STRENKOWSKIP"."FILM" 
   (        "ID_FILMU" NUMBER(*,0) NOT NULL ENABLE, 
        "TYTUŁ" VARCHAR2(100) NOT NULL ENABLE, 
        "DŁUGOŚĆ" NUMBER(*,0) NOT NULL ENABLE, 
        "WYDAWCA" VARCHAR2(100) NOT NULL ENABLE, 
        "REŻYSER" VARCHAR2(100) NOT NULL ENABLE, 
        "GATUNEK" VARCHAR2(100) NOT NULL ENABLE, 
         CONSTRAINT "FILM_PK" PRIMARY KEY ("ID_FILMU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "STRENKOWSKIP"."FILM_PK" ON "STRENKOWSKIP"."FILM" ("ID_FILMU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;




-- STRENKOWSKIP.SEANS definition

CREATE TABLE "STRENKOWSKIP"."SEANS" 
   (        "ID_SEANSU" NUMBER(*,0) NOT NULL ENABLE, 
        "ID_SALI" NUMBER(*,0) NOT NULL ENABLE, 
        "CENA_BAZOWA" FLOAT(126) DEFAULT 24.99 NOT NULL ENABLE, 
        "POCZĄTEK" TIMESTAMP (6) NOT NULL ENABLE, 
        "ID_FILMU" NUMBER(*,0) NOT NULL ENABLE, 
         CONSTRAINT "SEANS_PK" PRIMARY KEY ("ID_SEANSU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
         CONSTRAINT "SEANS_SALA_FK" FOREIGN KEY ("ID_SALI")
          REFERENCES "STRENKOWSKIP"."SALA" ("ID_SALI") ON DELETE CASCADE ENABLE, 
         CONSTRAINT "SEANS_FILM_FK" FOREIGN KEY ("ID_FILMU")
          REFERENCES "STRENKOWSKIP"."FILM" ("ID_FILMU") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "STRENKOWSKIP"."SEANS_PK" ON "STRENKOWSKIP"."SEANS" ("ID_SEANSU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;



-- STRENKOWSKIP.SALA definition

CREATE TABLE "STRENKOWSKIP"."SALA" 
   (        "ID_SALI" NUMBER(*,0) NOT NULL ENABLE, 
        "ILOŚĆ_MIEJSC" NUMBER(*,0) NOT NULL ENABLE, 
        "CZY_CZYNNA" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
        "ID_PLACÓWKI" NUMBER(*,0) DEFAULT 1 NOT NULL ENABLE, 
         CONSTRAINT "SALA_PK" PRIMARY KEY ("ID_SALI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
         CONSTRAINT "SALA_PLACÓWKA_FK" FOREIGN KEY ("ID_PLACÓWKI")
          REFERENCES "STRENKOWSKIP"."PLACÓWKA" ("ID_PLACÓWKI") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "STRENKOWSKIP"."SALA_PK" ON "STRENKOWSKIP"."SALA" ("ID_SALI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;




-- STRENKOWSKIP.PLACÓWKA definition

CREATE TABLE "STRENKOWSKIP"."PLACÓWKA" 
   (        "ID_PLACÓWKI" NUMBER(*,0) NOT NULL ENABLE, 
        "ADRES_PLACÓWKI" VARCHAR2(100) NOT NULL ENABLE, 
        "KOD_POCZTOWY" VARCHAR2(6) NOT NULL ENABLE, 
         CONSTRAINT "PLACÓWKA_PK" PRIMARY KEY ("ID_PLACÓWKI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE OR REPLACE EDITIONABLE TRIGGER "STRENKOWSKIP"."CHECK_POSTAL_CODE" 
        BEFORE INSERT OR UPDATE ON PLACÓWKA
        FOR EACH ROW
BEGIN
        IF NOT regexp_like(:NEW.KOD_POCZTOWY, '^[0-9]{2}-[0-9]{3}$') THEN 
                raise_application_error(-20001, 'Podano nieprawidłowy kod pocztowy');
        END IF;
END;
/
ALTER TRIGGER "STRENKOWSKIP"."CHECK_POSTAL_CODE" ENABLE;

CREATE UNIQUE INDEX "STRENKOWSKIP"."PLACÓWKA_PK" ON "STRENKOWSKIP"."PLACÓWKA" ("ID_PLACÓWKI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;





-- STRENKOWSKIP.ROLA definition

CREATE TABLE "STRENKOWSKIP"."ROLA" 
   (        "ID_ROLI" NUMBER(*,0) NOT NULL ENABLE, 
        "NAZWA" VARCHAR2(100) NOT NULL ENABLE, 
        "PENSJA_BAZOWA" FLOAT(126) DEFAULT 0 NOT NULL ENABLE, 
         CONSTRAINT "ROLA_PK" PRIMARY KEY ("ID_ROLI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "STRENKOWSKIP"."ROLA_PK" ON "STRENKOWSKIP"."ROLA" ("ID_ROLI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;