TRIGGER CHECK_SELLER_ROLE_TRIGGER
	BEFORE INSERT OR UPDATE ON TRANSAKCJA
	FOR EACH ROW
DECLARE 
	seller_role varchar(20);
BEGIN
	SELECT (ID_ROLI) INTO seller_role FROM UŻYTKOWNIK WHERE UŻYTKOWNIK.ID_UŻYTKOWNIKA = :NEW.ID_SPRZEDAWCY;
	IF seller_role = 1 THEN
		RAISE_APPLICATION_ERROR(-20001, 'Użytkownik podany jako sprzedawca nie ma uprawnień do sprzedaży');
	END IF;
END;