CREATE OR REPLACE TRIGGER STRENKOWSKIP.NEW_TRANSACTION_TRIGGER
	AFTER 
    INSERT 
    ON PRODUKT_TRANSAKCJA
    FOR EACH ROW 
DECLARE 
	qty NUMBER;
BEGIN
	SELECT ILOSC INTO qty FROM PRODUCTS WHERE PRODUCTS.PRODUCT_ID = :NEW.ID_PRODUKTU;
	IF :NEW.ILOSC_PRODUKTU <= qty THEN
		UPDATE PRODUCTS SET PRODUCTS.ILOSC = qty - :NEW.ILOSC_PRODUKTU WHERE PRODUCTS.PRODUCT_ID = :NEW.ID_PRODUKTU;
	END IF;
END; 