TRIGGER NEW_TICKET_VENUE_CAP_TRIGGER
	BEFORE INSERT OR UPDATE ON BILET
	FOR EACH ROW
DECLARE
	venue_cap NUMBER;
	tickets_for_seance NUMBER;
BEGIN
	SELECT (ILOŚĆ_MIEJSC) INTO venue_cap FROM SALA JOIN SEANS ON SEANS.ID_SALI = SALA.ID_SALI WHERE SEANS.ID_SEANSU = :NEW.ID_SEANSU;
	SELECT COUNT(ID_BILETU) INTO tickets_for_seance FROM BILET WHERE ID_SEANSU = :NEW.ID_SEANSU;
	IF venue_cap <= tickets_for_seance THEN
		RAISE_APPLICATION_ERROR(-20001, 'Wybrany seans został wyprzedany');
	END IF;
END;