CREATE OR REPLACE TRIGGER STRENKOWSKIP.NEW_TICKET_SEANCE_STARTED_TRIGGER
	BEFORE INSERT OR UPDATE ON BILET
	FOR EACH ROW
DECLARE 
	seance_start TIMESTAMP;
BEGIN
	SELECT (POCZĄTEK) INTO seance_start FROM SEANS WHERE SEANS.ID_SEANSU = :NEW.ID_SEANSU;
	IF seance_start < CURRENT_TIMESTAMP THEN
		RAISE_APPLICATION_ERROR(-20001, 'wybrany seans już się zaczął');
	END IF;
END;