TRIGGER NEW_TICKET_SEANCE_EXISTS_TRIGGER
	BEFORE INSERT OR UPDATE ON BILET
	FOR EACH ROW
DECLARE
	seances INTEGER;
BEGIN
	SELECT COUNT(*) INTO seances FROM SEANS WHERE SEANS.ID_SEANSU = :NEW.ID_SEANSU; 
	IF seances = 0 THEN
		RAISE_APPLICATION_ERROR(-20001, 'Seans o podanym ID_SEANSU nie istnieje.');
	END IF;
END;