CREATE OR REPLACE PROCEDURE STRENKOWSKIP.ADD_TICKET(
	seance_id NUMBER 
)
IS
	max_id NUMBER;
	seances NUMBER;
	seance_start TIMESTAMP;
	venue_cap NUMBER;
	tickets_for_seance NUMBER;
BEGIN
	SELECT GREATEST(ID_BILETU) INTO max_id FROM BILET;
	INSERT INTO BILET (ID_BILETU, ID_SEANSU) VALUES (max_id + 1, seance_id);
END ADD_TICKET;