CREATE OR REPLACE PROCEDURE STRENKOWSKIP.CREATE_ARCHIVE_ENTRY(
	USER_NAME VARCHAR2,
	METHOD_NAME VARCHAR2,
	ERROR_VALUE VARCHAR2,
	TABLE_NAME VARCHAR2
)
IS
	max_id INTEGER;
BEGIN
	SELECT MAX(ID_WPISU) INTO max_id FROM ARCHIWUM;
	max_id := max_id + 1;
	dbms_output.put_line(max_id);
	INSERT INTO ARCHIWUM (ID_WPISU, TABELA, OPERACJA, UZYTKOWNIK, DATA, BLAD) VALUES (max_id, TABLE_NAME, METHOD_NAME, USER_NAME, SYSDATE, ERROR_VALUE);

EXCEPTION

	WHEN NO_DATA_FOUND THEN
		INSERT INTO ARCHIWUM (ID_WPISU, TABELA, OPERACJA, UZYTKOWNIK, DATA) VALUES (max_id, TABLE_NAME, METHOD_NAME, USER_NAME, SYSDATE);

END CREATE_ARCHIVE_ENTRY;